### ISSUE TITLE
Design layout and implement the "Edit Organization" screen

### ISSUE THREAD

**Issue by kkiniaes** [rakshamuth/TheActivistWatch#2]

**Comment by raxsha** [comment]
Is this referring to the "View My Organizations" page?

**Comment by kkiniaes** [comment]
Sorry, I didn't see your comment here. It is referring to the "Edit Organization" page. I should've named this better, my apologies.

**Comment by kkiniaes** [comment]
Acceptance Criteria:
- [ ] I should be able to access this page from the "Organization Page" (the page on which I can view details regarding a given organization
- [ ] On this page, I should be able to edit all the same details I inputted when I created the organization
- [ ] I should also be able to mark another user as an admin by inputting the other user's username
- [ ] If I am not an admin of this organization, I should not be able to access this page
- [ ] I should also be able to remove an admin from this organization
- [ ] I should be able to remove myself as an admin, but only if there is another admin present
